# if set to true, handling of the request will be aborted if it takes longer than the specified timeout duration (client will receive a timeout response).
# If false, the request will continue to be processed even after the timeout has been reached.
abortOnTimeout = false

defaultTimeout = 5s

# operation-specific timeouts (overrides default timeout for the specified operation)
operationTimeout = {
  "receive-credentials-full": 10s
}