# walt.id Enterprise Service
# Base configuration

# Base domain of this service, e.g. `waltid.cloud`
baseDomain = "enterprise.localhost"
baseSsl = false
# Set basePort for internal Docker network communication
basePort = 7500
