# walt.id Enterprise Service
# Base configuration

# Base domain of this service, e.g. `waltid.cloud`
baseDomain = "enterprise.localhost"
baseSsl = false
basePort = 3000  # Required for Docker setup where API runs on port 3000
