resourceAccess = {

  s3-storage = {
    _type = "AwsS3Access"
    id = "s3-storage"
    region = "eu-north-1"
    bucket = { name = "my-bucket" }
    credentials = {
      _type = "AwsCredentials"
      accessKeyId = "abc"
      secretKey = "xyz"
    }
  }

  azure-storage = {
    _type = "AzureBlobAccess"
    id = "azure-storage"
    bucket = { 
    bucketName = "documents" 
    bucketUrl = "https://storage-name.blob.core.windows.net/bucket-name"
    }
    credentials = {
      _type = "AzureCredentials"
      connectionString = "DefaultEndpointsProtocol=https;AccountName=example;AccountKey=..."
    }
  }

  gcp-storage-main = {
    _type = "GcpStorageAccess"
    id = "gcp-storage-main"
    bucket = { name = "gcp-bucket-main" }
    projectId = "my-project"

    credentials = {
      _type = "GcpCredentials"
      serviceAccountKeyJson = {
        type = "service_account"
        project_id = "my-project"
        private_key_id = "abc123..."
        private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
        client_email = "service-account@my-project.iam.gserviceaccount.com"
        client_id = "1234567890"
        auth_uri = "https://accounts.google.com/o/oauth2/auth"
        token_uri = "https://oauth2.googleapis.com/token"
        auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
        client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/service-account%40my-project.iam.gserviceaccount.com"
        universe_domain = "googleapis.com"
      }
    }
  }
  
  aws-kms = {
    _type = "AwsKmsAccess"
    id = "aws-kms"
    region = "eu-central-1"
    credentials = {
      _type = "AwsCredentials"
      accessKeyId = "AK....F"
      secretKey = "6Y....Sr"
    }
  }
   azure-kms = {
      _type = "AzureKeyVaultAccess"
      id = "azure-kms"
      keyVaultUrl = "https://n2-keyvault.vault.azure.net/"
      credentials = {
        _type = "AzureCredentials"
        tenantId = "a8......46d"
        clientId = "3b......c2c"
        clientSecret = "1ZQ.......sc1n"
      }
    }
  
}