tokens = {
    "Mds5QLPTZXAlwersUJy79huvoetGK8BUUQua3v6gpbL5ZQLJGXUsTSy9rGbJIOdraG1ZPpya2QcM5ovgRjyHbaTmGfFaZLIqKmSJs8CCywAD4t9QajwfL7tOpMQbWBWc": {
        expiration = "2027-01-01T00:00:00Z", # Token has to be used by this expiration date
        account = {
            type = "email"
            identifier = { email = "superadmin@walt.id" }
            data = { password = ")ETvbky!I4j-]y+,H@bkkJ({UwycC.iBD5x(-OQ}]XH{(L1A[33Ac{*T" }
        }
    }
}
